apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- argocd.yaml
- cert-manager.yaml
- nfs-client.yaml
- fluentbit.yaml
- ingress-public.yaml
- ingress-private.yaml
- loki.yaml
# - prometheus-stack.yaml  # temporarily removed for reinstall
