apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backup-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backup-app
    spec:
      containers:
        - name: backup-app
          image: harbor.squid-ink.us/politeauthority/polite-cicd:0.0.12-dev
          imagePullPolicy: Always
          command:
            - tail
            - -f
            - /dev/null
      imagePullSecrets:
        - name: harbor-registry
